"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3%(@d$v3gxkbzlsa@p08w*ow8oaky&+2*3186txqvrtq5sr%n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HomePage',
    'referral_system',
    'rest_framework',
    'corsheaders',
]

AUTH_USER_MODEL = 'referral_system.CustomUser'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR/'media'


# CORS_ALLOWED_ORIGINS = [
#  '*'
# ]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

CORS_ALLOW_ALL_ORIGINS = True
# APPEND_SLASH=True

JAZZMIN_SETTINGS = {
    "site_title": "Monodo Admin",
    "site_header": "Monodo Control",
    "site_brand": "Monodo",
    "welcome_sign": "Welcome to Monodo Dashboard",
    "show_sidebar": True,
    "navigation_expanded": False,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Levels", "model": "referral_system.Level", "permissions": ["referral_system.view_level"]},
        {"name": "Users", "model": "referral_system.CustomUser", "permissions": ["referral_system.view_customuser"]},
        {"name": "Records", "model": "referral_system.Record", "permissions": ["referral_system.view_record"]},
        {"name": "Reviews", "model": "referral_system.Review", "permissions": ["referral_system.view_review"]},
        {"name": "Level Upgrades", "model": "referral_system.LevelUpgrade", "permissions": ["referral_system.view_levelupgrade"]},
        {"name": "Level Assignments", "model": "referral_system.LevelAssignment", "permissions": ["referral_system.view_levelassignment"]},
        {"name": "Login Activity", "model": "referral_system.LoginActivity", "permissions": ["referral_system.view_loginactivity"]},
        {"name": "Referral Tracking", "model": "referral_system.ReferralTracking", "permissions": ["referral_system.view_referraltracking"]},
    ],
    "icons": {
        "referral_system.CustomUser": "fas fa-users",
        "referral_system.Level": "fas fa-layer-group",
        "referral_system.Record": "fas fa-list-alt",
        "referral_system.Review": "fas fa-comments",
        "referral_system.LevelUpgrade": "fas fa-arrow-up",
        "referral_system.LevelAssignment": "fas fa-handshake",
        "referral_system.LoginActivity": "fas fa-chart-line",
        "auth.Group": "fas fa-user-shield",
    },
    "order_with_respect_to": [
        "referral_system.Level",
        "referral_system.CustomUser",
        "referral_system.Record",
        "referral_system.Review",
    ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "custom_js": [
        "admin/js/jazzmin_nav.js",
    ],
    "custom_css": [
        "admin/css/jazzmin_nav.css",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "theme": "pulse",
    "dark_mode_theme": "darkly",
    "dark_mode_switch": True,
    "footer_fixed": False,
}