# Generated by Django 5.2.7 on 2025-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Homepage_ImageDB',
            },
        ),
    ]
