# Generated by Django 5.2.7 on 2025-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='rating',
            field=models.FloatField(),
        ),
    ]
