# Generated by Django 5.2.7 on 2025-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_alter_carts_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='image',
            field=models.ImageField(upload_to='images/homepage'),
        ),
    ]
