# Generated by Django 5.2.7 on 2025-11-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_carts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='reveiw_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('balance', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'UserDB',
            },
        ),
        migrations.RenameModel(
            old_name='Carts',
            new_name='HomeCart',
        ),
    ]
