# Generated by Django 5.2.7 on 2025-11-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_reveiw_cart_user_rename_carts_homecart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='usr',
        ),
    ]
