# Generated by Django 5.2.7 on 2025-11-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_rename_user_usr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usr',
            new_name='User',
        ),
    ]
