# Generated by Django 5.2.7 on 2025-11-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_rename_usr_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeCart',
        ),
        migrations.DeleteModel(
            name='reveiw_cart',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
