# Generated by Django 5.2.7 on 2025-11-08 16:11

import django.db.models.deletion
import django.utils.timezone
import referral_system.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('BASIC', 'Basic'), ('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_upload_limit', models.IntegerField(default=10, help_text='Number of images user can upload per record')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage (e.g., 7.00 for 7%)', max_digits=5)),
                ('upgrade_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price to upgrade to this level (0 for free/default level)', max_digits=10)),
                ('priority_support', models.BooleanField(default=False, help_text='Get priority customer support')),
                ('featured_listing', models.BooleanField(default=False, help_text='Records appear as featured')),
                ('max_records_per_month', models.IntegerField(default=100, help_text='Maximum records per month')),
                ('level_order', models.IntegerField(default=0, help_text='Higher number = higher tier (1=Basic, 2=Gold, etc)')),
                ('icon_url', models.URLField(blank=True, help_text='URL for level badge/icon', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_text', models.TextField(help_text='The review content that will be shown to users')),
                ('is_active', models.BooleanField(default=True, help_text='Only active reviews will be included in APIs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('withdraw_password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('AGENT', 'Agent'), ('USER', 'Normal User')], default='USER', max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('level', models.ForeignKey(blank=True, help_text="User's membership level", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referral_system.level')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LevelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['SUPERADMIN', 'AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_levels', to=settings.AUTH_USER_MODEL)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_from_level', to='referral_system.level')),
                ('to_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_to_level', to='referral_system.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Assignment',
                'verbose_name_plural': 'Level Assignments',
                'db_table': 'level_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelUpgrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upgraded_at', models.DateTimeField(auto_now_add=True)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_from', to='referral_system.level')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_to', to='referral_system.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Upgrade',
                'verbose_name_plural': 'Level Upgrades',
                'db_table': 'level_upgrades',
                'ordering': ['-upgraded_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Unknown', help_text='City / Country if available', max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('accept_language', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('device_time', models.DateTimeField(blank=True, help_text='Client-reported device time (if provided)', null=True)),
                ('extra_metadata', models.JSONField(blank=True, help_text='Stores additional headers or info', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'db_table': 'login_activity',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='login_activ_user_id_147d46_idx'), models.Index(fields=['ip_address'], name='login_activ_ip_addr_e3ad30_idx'), models.Index(fields=['browser'], name='login_activ_browser_9200ef_idx'), models.Index(fields=['operating_system'], name='login_activ_operati_bf3c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AGENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tracking', to=settings.AUTH_USER_MODEL)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_tracking', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Tracking',
                'verbose_name_plural': 'Referral Trackings',
                'db_table': 'referral_tracking',
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='record_images/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage (auto-calculated from level if not provided)', max_digits=5)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin or Agent who created this record', limit_choices_to={'user_type__in': ['SUPERADMIN', 'AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(default=referral_system.models.Level.get_default_level_id, help_text='Level this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='referral_system.level')),
                ('reviews', models.ManyToManyField(blank=True, help_text='Selectable reviews shown with this record', related_name='records', to='referral_system.review')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'db_table': 'records',
                'ordering': ['level__level_order', 'title'],
                'indexes': [models.Index(fields=['level', 'status'], name='records_level_i_3c8ece_idx')],
            },
        ),
    ]
