# Generated by Django 5.2.7 on 2025-11-08 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['SUPERADMIN', 'AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
                'db_table': 'chat_threads',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'admin')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='referral_system.chatthread')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
