# Generated by Django 5.2.7 on 2025-11-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0002_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
