# Generated by Django 5.2.7 on 2025-11-09 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_remove_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this level as the default assigned to new members'),
        ),
        migrations.AddField(
            model_name='level',
            name='max_withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum amount a member can withdraw at once (0 means no limit)', max_digits=12),
        ),
        migrations.AddField(
            model_name='level',
            name='min_withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount a member can withdraw', max_digits=12),
        ),
        migrations.AddField(
            model_name='level',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum balance required to maintain this level', max_digits=12),
        ),
        migrations.AddField(
            model_name='level',
            name='orders_received_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of orders received while at this level'),
        ),
        migrations.AddField(
            model_name='level',
            name='withdrawals_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of withdrawals made while at this level'),
        ),
    ]
