# Generated by Django 5.2.7 on 2025-11-08 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_alter_record_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('BASIC', 'Basic'), ('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_upload_limit', models.IntegerField(default=10, help_text='Number of images user can upload per record')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage (e.g., 7.00 for 7%)', max_digits=5)),
                ('upgrade_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price to upgrade to this level (0 for free/default level)', max_digits=10)),
                ('priority_support', models.BooleanField(default=False, help_text='Get priority customer support')),
                ('featured_listing', models.BooleanField(default=False, help_text='Records appear as featured')),
                ('max_records_per_month', models.IntegerField(default=100, help_text='Maximum records per month')),
                ('level_order', models.IntegerField(default=0, help_text='Higher number = higher tier (1=Basic, 2=Gold, etc)')),
                ('icon_url', models.URLField(blank=True, help_text='URL for level badge/icon', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['level_order'],
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
        migrations.AlterField(
            model_name='record',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Commission percentage (auto-calculated from user's level)", max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, help_text="User's membership level", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referral_system.level'),
        ),
        migrations.CreateModel(
            name='LevelUpgrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upgraded_at', models.DateTimeField(auto_now_add=True)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_from', to='referral_system.level')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_to', to='referral_system.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Upgrade',
                'verbose_name_plural': 'Level Upgrades',
                'db_table': 'level_upgrades',
                'ordering': ['-upgraded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='record_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='referral_system.record')),
            ],
            options={
                'verbose_name': 'Record Image',
                'verbose_name_plural': 'Record Images',
                'db_table': 'record_images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
