# Generated by Django 5.2.7 on 2025-11-08 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_level_remove_record_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['SUPERADMIN', 'AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_levels', to=settings.AUTH_USER_MODEL)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_from_level', to='referral_system.level')),
                ('to_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_to_level', to='referral_system.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Assignment',
                'verbose_name_plural': 'Level Assignments',
                'db_table': 'level_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
