# Generated by Django 5.2.7 on 2025-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0005_levelassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='record_images/'),
        ),
        migrations.DeleteModel(
            name='RecordImage',
        ),
    ]
