# Generated by Django 5.2.7 on 2025-11-09 11:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0005_alter_customuser_id_alter_level_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current withdrawable earnings', max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats_last_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='todays_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='todays_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission earned by the user', max_digits=12),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_percentage_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='referral_system.record')),
                ('selected_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='referral_system.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ASSIGNED')), fields=('user', 'record'), name='unique_active_task_per_record')],
            },
        ),
    ]
