# Generated by Django 5.2.7 on 2025-11-08 08:14

import django.db.models.deletion
import referral_system.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0006_record_image_delete_recordimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['level__level_order', 'title'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='records_status_3fc695_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='records_user_id_7f4bbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='records_agent_i_2bb521_idx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='record',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin or Agent who created this record', limit_choices_to={'user_type__in': ['SUPERADMIN', 'AGENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='level',
            field=models.ForeignKey(default=referral_system.models.Level.get_default_level, help_text='Level this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='referral_system.level'),
        ),
        migrations.AlterField(
            model_name='record',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage (auto-calculated from level if not provided)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['level', 'status'], name='records_level_i_3c8ece_idx'),
        ),
    ]
