# Generated by Django 5.2.7 on 2025-11-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0006_customuser_current_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_earnings',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stats_last_reset',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='todays_commission',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='todays_orders',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_balance',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
