# Generated by Django 5.2.7 on 2025-11-08 08:16

import django.db.models.deletion
import referral_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0007_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.ForeignKey(default=referral_system.models.Level.get_default_level_id, help_text='Level this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='referral_system.level'),
        ),
    ]
