# Generated by Django 5.2.7 on 2025-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0007_remove_customuser_current_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='taking_orders_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
