# Generated by Django 5.2.7 on 2025-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0008_alter_record_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
