# Generated by Django 5.2.7 on 2025-11-09 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0008_customuser_taking_orders_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=12),
        ),
    ]
