# Generated by Django 5.2.7 on 2025-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0009_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
