# Generated by Django 5.2.7 on 2025-11-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0010_customuser_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
    ]
