# Generated by Django 5.2.7 on 2025-11-16 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0011_remove_referral_and_membership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, help_text="User's membership level", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referral_system.level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
