# Generated by Django 5.2.7 on 2025-11-16 08:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0012_customuser_level_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_withdrawal',
            field=models.BooleanField(default=True, help_text='Whether user is allowed to withdraw'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_daily_order',
            field=models.PositiveIntegerField(default=0, help_text='Available orders for today'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='credibility',
            field=models.IntegerField(default=100, help_text='Credibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='frozen_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount frozen/held', max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rob_single',
            field=models.BooleanField(default=False, help_text='Rob Single status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='todays_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission earned today', max_digits=12),
        ),
    ]
