# Generated by Django 5.2.7 on 2025-11-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0013_add_user_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['id'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['level__id', 'title'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.RemoveField(
            model_name='level',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='level',
            name='featured_listing',
        ),
        migrations.RemoveField(
            model_name='level',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='level',
            name='image_upload_limit',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_order',
        ),
        migrations.RemoveField(
            model_name='level',
            name='max_records_per_month',
        ),
        migrations.RemoveField(
            model_name='level',
            name='priority_support',
        ),
        migrations.RemoveField(
            model_name='level',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='upgrade_price',
        ),
    ]
