# Generated by Django 5.2.7 on 2025-11-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0014_simplify_level_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='operate',
            field=models.CharField(blank=True, help_text='Operation details', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.CharField(blank=True, help_text='Place/Location', max_length=255, null=True),
        ),
    ]
