# Generated by Django 5.2.7 on 2025-11-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0015_add_operate_place_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.ForeignKey(blank=True, default=None, help_text='Level this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='referral_system.level'),
        ),
    ]
