# Generated by Django 5.2.7 on 2025-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0016_allow_null_level_in_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_orders_made',
            field=models.PositiveIntegerField(default=0, help_text='Current number of orders made by the user'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orders_received_today',
            field=models.PositiveIntegerField(default=0, help_text='Orders received today'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_continuous_orders_after',
            field=models.PositiveIntegerField(default=0, help_text='Start continuous orders after this many orders'),
        ),
    ]
