# Generated by Django 5.2.7 on 2025-11-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0017_add_order_tracking_and_user_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, help_text="Position/order in the user's product list (lower number = earlier in queue)")),
                ('is_active', models.BooleanField(default=True, help_text="Whether this product is active in the user's list")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(help_text='Product/Record assigned to this user', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='referral_system.record')),
                ('user', models.ForeignKey(help_text='User who owns this product assignment', on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Product',
                'verbose_name_plural': 'User Products',
                'db_table': 'user_products',
                'ordering': ['user', 'position', 'created_at'],
                'indexes': [models.Index(fields=['user', 'position'], name='user_produc_user_id_ee0b43_idx'), models.Index(fields=['user', 'is_active'], name='user_produc_user_id_dd43da_idx')],
                'unique_together': {('user', 'record')},
            },
        ),
    ]
